'use strict';

/**
 * src/defects/taxonomy.js
 *
 * Authoritative 10-Defect Categorization Taxonomy & Threshold Definitions for ctc v2.
 */

const DEFECT_CATEGORIES = Object.freeze({
  MISSING_ELEMENT: 'MISSING_ELEMENT',
  MARGIN_SHIFT: 'MARGIN_SHIFT',
  CONTRAST_FAILURE: 'CONTRAST_FAILURE',
  COLOR_COLLAPSE: 'COLOR_COLLAPSE',
  TOUCH_TARGET_TOO_SMALL: 'TOUCH_TARGET_TOO_SMALL',
  INVARIANT_BROKEN: 'INVARIANT_BROKEN',
  EPD_FLASH_DETECTED: 'EPD_FLASH_DETECTED',
  LAYOUT_OVERFLOW: 'LAYOUT_OVERFLOW',
  ASSET_MISSING: 'ASSET_MISSING',
  EVIDENCE_MISSING: 'EVIDENCE_MISSING'
});

const TAXONOMY_ERROR_CODES = Object.freeze({
  ELEMENT_NOT_RENDERED: 'MISSING_ELEMENT',
  GEOMETRY_DRIFT: 'MARGIN_SHIFT',
  SPATIAL_DRIFT_EXCEEDED: 'MARGIN_SHIFT',
  BASELINE_MISALIGNMENT: 'MARGIN_SHIFT',
  LAYOUT_GEOMETRY_INVALID: 'MARGIN_SHIFT',
  INVALID_COORDINATE_DATA: 'MARGIN_SHIFT',
  HARDWARE_INSET_MISMATCH: 'MARGIN_SHIFT',
  CONTRAST_COLLAPSE: 'CONTRAST_FAILURE',
  CONTRAST_VIOLATION: 'CONTRAST_FAILURE',
  COLOR_COLLAPSE: 'COLOR_COLLAPSE',
  TOUCH_TARGET_VIOLATION: 'TOUCH_TARGET_TOO_SMALL',
  TOUCH_TARGET_COLLAPSE: 'TOUCH_TARGET_TOO_SMALL',
  TOUCH_TARGET_TOO_SMALL: 'TOUCH_TARGET_TOO_SMALL',
  BEHAVIOR_INVARIANT_VIOLATED: 'INVARIANT_BROKEN',
  INVARIANT_VIOLATION: 'INVARIANT_BROKEN',
  INVARIANT_PERSISTENCE_VIOLATION: 'INVARIANT_BROKEN',
  INVARIANT_AUTOSAVE_VIOLATION: 'INVARIANT_BROKEN',
  INVARIANT_NAVIGATION_VIOLATION: 'INVARIANT_BROKEN',
  INVARIANT_BROKEN: 'INVARIANT_BROKEN',
  EPD_WORKAROUND_VIOLATION: 'EPD_FLASH_DETECTED',
  LAYOUT_CLIPPING_OVERFLOW: 'LAYOUT_OVERFLOW',
  LAYOUT_VIEWPORT_OVERFLOW: 'LAYOUT_OVERFLOW',
  ASSET_RESOURCE_MISSING: 'ASSET_MISSING',
  FONT_RESOURCE_MISSING: 'ASSET_MISSING',
  ASSET_HASH_MISMATCH: 'ASSET_MISSING',
  PREVIEW_RENDER_MISSING: 'EVIDENCE_MISSING',
  CONTRACT_EVIDENCE_MISSING: 'EVIDENCE_MISSING',
  HARDWARE_LEASE_TIMEOUT: 'EVIDENCE_MISSING',
  COMPILATION_ERROR: 'INVARIANT_BROKEN',
  STATE_RESTORATION_FAILURE: 'INVARIANT_BROKEN',
  SCENARIO_REPLAY_MISMATCH: 'INVARIANT_BROKEN',
  INK_IOU_BELOW_THRESHOLD: 'LAYOUT_OVERFLOW',
  SOBEL_CONTOUR_BELOW_THRESHOLD: 'LAYOUT_OVERFLOW',
  HARD_MARGIN_SHIFT_VETO: 'MARGIN_SHIFT'
});

const THRESHOLDS = Object.freeze({
  MAX_SPATIAL_DRIFT_PX: 3.0,
  MAX_BASELINE_DRIFT_PX: 2.0,
  HARD_MARGIN_SHIFT_VETO_PX: 10.0,
  MIN_CONTRAST_RATIO_NORMAL: 4.5,
  MIN_CONTRAST_RATIO_LARGE: 3.0,
  MIN_CONTRAST_RATIO_AAA: 7.0,
  MIN_TOUCH_TARGET_DP: 48.0,
  MIN_TOUCH_TARGET_PX: 96.0,
  MIN_INK_IOU: 85.0,
  MIN_CONTOUR_SCORE: 90.0,
  MIN_MSSIM: 0.90,
  MAX_DC1_SETTLE_MS: 150.0,
  MIN_DC1_SETTLE_MS: 150.0,
  MAX_ACCEPTABLE_FRAME_SETTLE_MS: 300.0,
  PROHIBITED_SETTLE_PAUSE_MS: 500.0
});

module.exports = {
  DEFECT_CATEGORIES,
  TAXONOMY_ERROR_CODES,
  THRESHOLDS
};
