package com.claude.compose.screen

import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.minimumInteractiveComponentSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathMeasure
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.rotate
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.claude.compose.R
import com.claude.compose.theme.AbcArizonaFlare
import com.claude.compose.theme.AbcArizonaFlareHeadline
import com.claude.compose.theme.AbcArizonaSans
import com.claude.compose.theme.AbcRomMono

/**
 * GeneratedDc1Screen
 *
 * Generated by Claude-to-Compose v2 Design Compiler.
 * Target display: Daylight Computer (DC1) 10.5in 4:3 LivePaper (1184 x 1584 px @ 2x density).
 * Zero EPD waveforms; standard Android SurfaceFlinger 60Hz-120Hz pipeline.
 */
@Composable
fun GeneratedDc1Screen(
    onSkipClick: () -> Unit = {},
    onGetStartedClick: () -> Unit = {},
    onChipSelected: (String) -> Unit = {},
    modifier: Modifier = Modifier
) {
    var selectedChip by rememberSaveable { mutableStateOf("Footprints") }

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(Color.White)
            .testTag("daylight#onboarding/root")
    ) {
    // Double Hairline Reference Frames (Fidelity-First)
    Canvas(modifier = Modifier.fillMaxSize().testTag("daylight#onboarding/frames")) {
        val outerColor = Color(0xFFA8A8A0)
        val innerColor = Color(0xFFDCD5C9).copy(alpha = 0.6f)

        val outerLeft = 27.25.dp.toPx()
        val outerRight = size.width - 26.5.dp.toPx()
        val outerTop = 26.5.dp.toPx()
        val outerBottom = 680.dp.toPx()

        val innerLeft = 34.dp.toPx()
        val innerRight = size.width - 33.5.dp.toPx()
        val innerTop = 34.dp.toPx()
        val innerBottom = 650.dp.toPx()

        // Outer Frame (top + sides with rounded top corners)
        val outerPath = Path().apply {
            moveTo(outerLeft, outerBottom)
            lineTo(outerLeft, outerTop + 4.dp.toPx())
            quadraticTo(outerLeft, outerTop, outerLeft + 4.dp.toPx(), outerTop)
            lineTo(outerRight - 4.dp.toPx(), outerTop)
            quadraticTo(outerRight, outerTop, outerRight, outerTop + 4.dp.toPx())
            lineTo(outerRight, outerBottom)
        }
        drawPath(outerPath, color = outerColor, style = Stroke(width = 1.4.dp.toPx()))

        // Inner Frame (top + sides with rounded top corners)
        val innerPath = Path().apply {
            moveTo(innerLeft, innerBottom)
            lineTo(innerLeft, innerTop + 2.dp.toPx())
            quadraticTo(innerLeft, innerTop, innerLeft + 2.dp.toPx(), innerTop)
            lineTo(innerRight - 2.dp.toPx(), innerTop)
            quadraticTo(innerRight, innerTop, innerRight, innerTop + 2.dp.toPx())
            lineTo(innerRight, innerBottom)
        }
        drawPath(innerPath, color = innerColor, style = Stroke(width = 1.dp.toPx()))
    }

    Surface(
        onClick = onSkipClick,
        shape = RoundedCornerShape(11.dp),
        color = Color.White,
        border = BorderStroke(1.dp, Color(0xFFDCD5C9)),
        modifier = Modifier
            .align(Alignment.TopEnd)
            .padding(top = 13.dp, end = 18.dp)
            .testTag("daylight#onboarding/nav/skip")
            .minimumInteractiveComponentSize()
            .size(width = 48.dp, height = 32.dp)
    ) {
        Box(contentAlignment = Alignment.Center) {
            Text(
                text = "Skip",
                fontFamily = AbcArizonaSans,
                fontSize = 12.sp,
                fontWeight = FontWeight.Normal,
                color = Color(0xFF1A1A1A)
            )
        }
    }

    // Hero Illustration Canvas: Architectural Grid, Building Lots, and Footprint Tracks (Fidelity-First)
    GeneratedDc1BackgroundCanvas(
        modifier = Modifier
            .fillMaxSize()
            .testTag("daylight#onboarding/hero/illustration")
    )

    // Upper-Right Compass Rose Graphic (Fidelity-First)
    GeneratedCompassRoseGraphic(
        modifier = Modifier
            .align(Alignment.TopEnd)
            .padding(top = 102.5.dp, end = 56.5.dp)
            .testTag("daylight#onboarding/hero/compass")
            .size(68.dp)
    )

    // Daylight Brand Logo Glyph (Native Asset)
    Image(
        painter = painterResource(id = R.drawable.daylight_logo),
        contentDescription = "daylight#onboarding/hero/brand_glyph",
        modifier = Modifier
        .align(Alignment.TopCenter)
        .padding(top = 410.dp)
            .testTag("daylight#onboarding/hero/brand_glyph")
            .size(42.dp)
    )

    Text(
        text = "Daylight DC1 · the living page",
        fontFamily = FontFamily.Monospace,
        fontSize = 12.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 15.sp,
        letterSpacing = (1.1).sp,
        color = Color(0xFF535353),
        textAlign = TextAlign.Center,
        modifier = Modifier
        .testTag("daylight#onboarding/typography/kicker")
        .fillMaxWidth()
        .padding(top = 468.dp)
    )

    Text(
        text = "Step into daylight",
        fontFamily = AbcArizonaFlare,
        fontSize = 44.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 48.sp,
        letterSpacing = (-3.05).sp,
        color = Color(0xFF000000),
        textAlign = TextAlign.Center,
        modifier = Modifier
        .testTag("daylight#onboarding/typography/headline")
        .fillMaxWidth()
        .padding(top = 489.7.dp)
    )

    Text(
        text = "A reflective paper screen that moves like ink — 60 to\n120 frames a second, and not a drop of blue light.\nLet's make it yours.",
        fontFamily = AbcArizonaSans,
        fontSize = 14.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 20.sp,
        color = Color(0xFF343434),
        textAlign = TextAlign.Center,
        modifier = Modifier
        .testTag("daylight#onboarding/typography/subtitle")
        .fillMaxWidth()
        .padding(start = 2.1.dp)
        .padding(top = 550.7.dp)
    )

    Surface(
        onClick = onGetStartedClick,
        shape = RoundedCornerShape(21.dp),
        color = Color(0xFF000000),
        border = null,
        modifier = Modifier
            .align(Alignment.TopCenter)
            .padding(top = 632.5.dp)
            .testTag("daylight#onboarding/action/get_started")
            .minimumInteractiveComponentSize()
            .size(width = 125.dp, height = 42.dp)
    ) {
        Box(contentAlignment = Alignment.Center) {
            Text(
                text = "Get started",
                fontFamily = AbcArizonaSans,
                fontSize = 15.sp,
                fontWeight = FontWeight.Medium,
                color = Color.White
            )
        }
    }

    // Paper Motion Interactive Selection Chips (Sol:OS Native Chip Row)
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier
            .fillMaxWidth()
            .testTag("daylight#onboarding/chips/container")
            .padding(top = 699.dp)
    ) {
        // Row 1 Chips with inline kicker label
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(6.dp, Alignment.CenterHorizontally),
            modifier = Modifier.fillMaxWidth()
        ) {
            Text(
                text = "PAPER MOTION",
                fontSize = 8.5.sp,
                fontWeight = FontWeight.SemiBold,
                fontFamily = FontFamily.Monospace,
                letterSpacing = 0.5.sp,
                color = Color(0xFF535353),
                modifier = Modifier.padding(end = 1.dp)
            )
            DaylightChip(
                text = "Footprints",
                isSelected = (selectedChip == "Footprints"),
                onClick = { onChipSelected("Footprints") },
                sourceId = "daylight#onboarding/chips/container/chip_0"
            )
            DaylightChip(
                text = "Contours",
                isSelected = (selectedChip == "Contours"),
                onClick = { onChipSelected("Contours") },
                sourceId = "daylight#onboarding/chips/container/chip_1"
            )
            DaylightChip(
                text = "Filigree",
                isSelected = (selectedChip == "Filigree"),
                onClick = { onChipSelected("Filigree") },
                sourceId = "daylight#onboarding/chips/container/chip_2"
            )
            DaylightChip(
                text = "Flow",
                isSelected = (selectedChip == "Flow"),
                onClick = { onChipSelected("Flow") },
                sourceId = "daylight#onboarding/chips/container/chip_3"
            )
            DaylightChip(
                text = "Whorls",
                isSelected = (selectedChip == "Whorls"),
                onClick = { onChipSelected("Whorls") },
                sourceId = "daylight#onboarding/chips/container/chip_4"
            )
            DaylightChip(
                text = "Feather",
                isSelected = (selectedChip == "Feather"),
                onClick = { onChipSelected("Feather") },
                sourceId = "daylight#onboarding/chips/container/chip_5"
            )
        }
        
        Spacer(modifier = Modifier.height(7.dp))
        
        // Row 2 Chips
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(6.dp, Alignment.CenterHorizontally),
            modifier = Modifier.fillMaxWidth()
        ) {
            DaylightChip(
                text = "Streets",
                isSelected = (selectedChip == "Streets"),
                onClick = { onChipSelected("Streets") },
                sourceId = "daylight#onboarding/chips/container/chip_r2_0"
            )
            DaylightChip(
                text = "Sunrise",
                isSelected = (selectedChip == "Sunrise"),
                onClick = { onChipSelected("Sunrise") },
                sourceId = "daylight#onboarding/chips/container/chip_r2_1"
            )
        }
    }
    }
}

@Composable
private fun DaylightChip(
    text: String,
    isSelected: Boolean,
    onClick: () -> Unit,
    sourceId: String,
    modifier: Modifier = Modifier
) {
    val bgColor = if (isSelected) Color(0xFF000000) else Color(0x0F000000)
    val textColor = if (isSelected) Color(0xFFFFFFFF) else Color(0xFF535353)

    Box(
        modifier = modifier
            .testTag(sourceId)
            .clip(RoundedCornerShape(13.dp))
            .background(bgColor)
            .clickable(onClick = onClick)
            .padding(horizontal = 6.dp, vertical = 5.dp)
    ) {
        Text(
            text = text,
            fontFamily = AbcArizonaSans,
            fontSize = 11.sp,
            fontWeight = if (isSelected) FontWeight.Medium else FontWeight.Normal,
            color = textColor
        )
    }
}

@Composable
private fun GeneratedCompassRoseGraphic(modifier: Modifier = Modifier) {
    Canvas(modifier = modifier) {
        val c = Offset(size.width / 2f, size.height / 2f)
        val r = size.minDimension / 2f

        // Outer Ring
        drawCircle(
            color = Color(0xFF000000),
            radius = r * 0.96f,
            center = c,
            style = Stroke(width = 1.2.dp.toPx())
        )

        // Inner Concentric Ring
        drawCircle(
            color = Color(0xFF858585),
            radius = r * 0.70f,
            center = c,
            style = Stroke(width = 1.dp.toPx())
        )

        // 4 Diagonal Ticks
        val tickR1 = r * 0.38f
        val tickR2 = r * 0.68f
        val angles = listOf(45f, 135f, 225f, 315f)
        angles.forEach { angle ->
            val rad = Math.toRadians(angle.toDouble())
            val cos = Math.cos(rad).toFloat()
            val sin = Math.sin(rad).toFloat()
            drawLine(
                color = Color(0xFF535353),
                start = Offset(c.x + cos * tickR1, c.y + sin * tickR1),
                end = Offset(c.x + cos * tickR2, c.y + sin * tickR2),
                strokeWidth = 1.dp.toPx()
            )
        }

        // 4-Point Star Cardinal Points with two-tone shading
        val spikeLen = r * 0.94f
        val baseW = r * 0.16f

        // North Point
        val northLeft = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x - baseW, c.y)
            lineTo(c.x, c.y - spikeLen)
            close()
        }
        val northRight = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x + baseW, c.y)
            lineTo(c.x, c.y - spikeLen)
            close()
        }
        drawPath(northLeft, color = Color(0xFF535353))
        drawPath(northRight, color = Color(0xFF343434))

        // South Point
        val southLeft = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x - baseW, c.y)
            lineTo(c.x, c.y + spikeLen)
            close()
        }
        val southRight = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x + baseW, c.y)
            lineTo(c.x, c.y + spikeLen)
            close()
        }
        drawPath(southLeft, color = Color(0xFF343434))
        drawPath(southRight, color = Color(0xFF535353))

        // East Point
        val eastTop = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x, c.y - baseW)
            lineTo(c.x + spikeLen, c.y)
            close()
        }
        val eastBottom = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x + baseW, c.y)
            lineTo(c.x + spikeLen, c.y)
            close()
        }
        drawPath(eastTop, color = Color(0xFF535353))
        drawPath(eastBottom, color = Color(0xFF343434))

        // West Point
        val westTop = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x, c.y - baseW)
            lineTo(c.x - spikeLen, c.y)
            close()
        }
        val westBottom = Path().apply {
            moveTo(c.x, c.y)
            lineTo(c.x, c.y + baseW)
            lineTo(c.x - spikeLen, c.y)
            close()
        }
        drawPath(westTop, color = Color(0xFF343434))
        drawPath(westBottom, color = Color(0xFF535353))
    }
}

@Composable
private fun GeneratedDc1BackgroundCanvas(modifier: Modifier = Modifier) {
    Canvas(modifier = modifier) {
        // 1. Cartesian Grid Lines
        val vertGridSegments = listOf(
            Triple(69.5.dp, 100.5.dp, 221.0.dp),
            Triple(69.5.dp, 249.0.dp, 255.5.dp),
            Triple(110.5.dp, 127.0.dp, 226.0.dp),
            Triple(110.5.dp, 259.0.dp, 265.5.dp),
            Triple(150.0.dp, 90.0.dp, 264.0.dp),
            Triple(150.0.dp, 265.0.dp, 296.5.dp),
            Triple(150.0.dp, 299.5.dp, 365.0.dp),
            Triple(188.5.dp, 179.0.dp, 209.5.dp),
            Triple(188.5.dp, 213.5.dp, 267.0.dp),
            Triple(188.5.dp, 268.5.dp, 309.5.dp),
            Triple(229.0.dp, 182.5.dp, 264.0.dp),
            Triple(271.0.dp, 103.5.dp, 273.0.dp),
            Triple(271.0.dp, 274.5.dp, 365.0.dp),
            Triple(314.0.dp, 111.0.dp, 119.5.dp),
            Triple(314.0.dp, 135.0.dp, 277.5.dp),
            Triple(314.0.dp, 279.0.dp, 289.5.dp),
            Triple(355.5.dp, 149.0.dp, 155.5.dp),
            Triple(355.5.dp, 170.0.dp, 272.5.dp),
            Triple(395.0.dp, 110.0.dp, 204.5.dp),
            Triple(395.0.dp, 207.0.dp, 283.0.dp),
            Triple(395.0.dp, 284.0.dp, 352.0.dp),
            Triple(433.5.dp, 146.0.dp, 265.0.dp),
            Triple(433.5.dp, 268.0.dp, 279.5.dp),
            Triple(433.5.dp, 281.0.dp, 292.0.dp),
            Triple(473.0.dp, 188.5.dp, 259.0.dp),
            Triple(514.5.dp, 132.0.dp, 137.5.dp),
            Triple(514.5.dp, 175.0.dp, 252.0.dp),
            Triple(514.5.dp, 253.5.dp, 313.0.dp),
            Triple(557.5.dp, 90.5.dp, 226.5.dp),
            Triple(557.5.dp, 228.0.dp, 288.0.dp)
        )
        for ((xDp, startYDp, endYDp) in vertGridSegments) {
            drawLine(
                color = Color(0xFF858585),
                start = Offset(xDp.toPx(), startYDp.toPx()),
                end = Offset(xDp.toPx(), endYDp.toPx()),
                strokeWidth = 1f
            )
        }

        val horizGridSegments = listOf(
            Triple(98.5.dp, 34.0.dp, 112.5.dp),
            Triple(98.5.dp, 305.0.dp, 314.0.dp),
            Triple(149.0.dp, 34.0.dp, 146.0.dp),
            Triple(149.0.dp, 350.5.dp, 357.0.dp),
            Triple(200.0.dp, 34.0.dp, 104.0.dp),
            Triple(200.0.dp, 384.0.dp, 390.5.dp),
            Triple(250.5.dp, 34.0.dp, 76.5.dp),
            Triple(250.5.dp, 80.5.dp, 103.5.dp),
            Triple(301.5.dp, 34.0.dp, 140.5.dp),
            Triple(353.0.dp, 34.0.dp, 120.0.dp),
            Triple(353.0.dp, 121.5.dp, 221.5.dp)
        )
        for ((yDp, startXDp, endXDp) in horizGridSegments) {
            drawLine(
                color = Color(0xFF858585),
                start = Offset(startXDp.toPx(), yDp.toPx()),
                end = Offset(endXDp.toPx(), yDp.toPx()),
                strokeWidth = 1f
            )
        }

        // 2. Rectangular Building / Lot Outlines
        val lotOutlines = listOf(
            Offset(76.dp.toPx(), 177.dp.toPx()) to Size(44.dp.toPx(), 32.dp.toPx()),
            Offset(210.5.dp.toPx(), 156.5.dp.toPx()) to Size(29.5.dp.toPx(), 30.dp.toPx()),
            Offset(269.dp.toPx(), 176.dp.toPx()) to Size(33.dp.toPx(), 22.dp.toPx()),
            Offset(317.dp.toPx(), 140.dp.toPx()) to Size(18.5.dp.toPx(), 18.5.dp.toPx()),
            Offset(380.dp.toPx(), 220.dp.toPx()) to Size(27.dp.toPx(), 29.dp.toPx()),
            Offset(503.5.dp.toPx(), 173.dp.toPx()) to Size(41.5.dp.toPx(), 28.5.dp.toPx()),
            Offset(341.5.dp.toPx(), 168.dp.toPx()) to Size(41.dp.toPx(), 25.dp.toPx()),
            Offset(418.5.dp.toPx(), 310.dp.toPx()) to Size(34.dp.toPx(), 20.dp.toPx()),
            Offset(186.dp.toPx(), 339.dp.toPx()) to Size(37.dp.toPx(), 17.dp.toPx()),
            Offset(388.dp.toPx(), 328.dp.toPx()) to Size(40.5.dp.toPx(), 12.5.dp.toPx()),
            Offset(345.dp.toPx(), 385.5.dp.toPx()) to Size(37.dp.toPx(), 25.dp.toPx()),
            Offset(300.dp.toPx(), 375.dp.toPx()) to Size(40.dp.toPx(), 22.dp.toPx()),
            Offset(255.dp.toPx(), 424.dp.toPx()) to Size(34.dp.toPx(), 25.dp.toPx()),
            Offset(270.dp.toPx(), 458.dp.toPx()) to Size(32.dp.toPx(), 18.dp.toPx()),
            Offset(410.dp.toPx(), 470.dp.toPx()) to Size(42.dp.toPx(), 25.dp.toPx()),
            Offset(486.dp.toPx(), 411.dp.toPx()) to Size(25.dp.toPx(), 20.dp.toPx()),
            Offset(108.dp.toPx(), 540.dp.toPx()) to Size(30.dp.toPx(), 28.dp.toPx()),
            Offset(440.dp.toPx(), 590.dp.toPx()) to Size(40.dp.toPx(), 22.dp.toPx())
        )

        lotOutlines.forEach { (pos, size) ->
            drawRoundRect(
                color = Color(0xFF343434),
                topLeft = pos,
                size = size,
                cornerRadius = CornerRadius(2f, 2f),
                style = Stroke(width = 1.2f)
            )
        }

        // 3. Lane 1: Diagonal curve with double rails, closed cap, and alternating footprints
        val lane1 = Path().apply {
            moveTo(280.5.dp.toPx(), 75.dp.toPx())
            cubicTo(
                350.dp.toPx(), 155.dp.toPx(),
                440.dp.toPx(), 255.dp.toPx(),
                462.dp.toPx(), 370.dp.toPx()
            )
            cubicTo(
                465.dp.toPx(), 430.dp.toPx(),
                440.dp.toPx(), 500.dp.toPx(),
                385.dp.toPx(), 560.dp.toPx()
            )
            cubicTo(
                350.dp.toPx(), 610.dp.toPx(),
                330.dp.toPx(), 655.dp.toPx(),
                325.dp.toPx(), 700.dp.toPx()
            )
        }
        drawLaneWithFootprints(lane1, railSpacing = 4.dp.toPx(), footprintStep = 18.dp.toPx(), roundedStartCap = false)

        // 4. Lane 2: Horizontal curve across middle
        val lane2 = Path().apply {
            moveTo(18.dp.toPx(), 223.dp.toPx())
            cubicTo(
                120.dp.toPx(), 260.dp.toPx(),
                240.dp.toPx(), 270.dp.toPx(),
                360.dp.toPx(), 281.dp.toPx()
            )
            cubicTo(
                430.dp.toPx(), 286.dp.toPx(),
                510.dp.toPx(), 265.dp.toPx(),
                560.dp.toPx(), 226.dp.toPx()
            )
        }
        drawLaneWithFootprints(lane2, railSpacing = 4.dp.toPx(), footprintStep = 18.dp.toPx(), roundedStartCap = false)

        // 5. Lane 3: Left vertical/diagonal curve with rounded dome top cap
        val lane3 = Path().apply {
            moveTo(208.dp.toPx(), 92.dp.toPx())
            cubicTo(
                205.dp.toPx(), 180.dp.toPx(),
                175.dp.toPx(), 260.dp.toPx(),
                116.dp.toPx(), 360.dp.toPx()
            )
            cubicTo(
                65.dp.toPx(), 460.dp.toPx(),
                40.dp.toPx(), 560.dp.toPx(),
                30.dp.toPx(), 670.dp.toPx()
            )
        }
        drawTwoRailLane(lane3, railSpacing = 3.5.dp.toPx(), roundedStartCap = true)

        // 6. Lane 4: Lower subtle curve passing behind text
        val lane4 = Path().apply {
            moveTo(45.dp.toPx(), 575.dp.toPx())
            cubicTo(
                180.dp.toPx(), 530.dp.toPx(),
                380.dp.toPx(), 522.dp.toPx(),
                532.dp.toPx(), 504.dp.toPx()
            )
        }
        drawTwoRailLane(lane4, railSpacing = 3.5.dp.toPx(), roundedStartCap = false)
    }
}

private fun DrawScope.drawTwoRailLane(path: Path, railSpacing: Float, roundedStartCap: Boolean = false) {
    val measure = PathMeasure()
    measure.setPath(path, forceClosed = false)
    val length = measure.length
    val halfSpace = railSpacing / 2f

    // Thick white fill underneath to mask grid lines
    drawPath(path, color = Color.White, style = Stroke(width = railSpacing + 2f, cap = if (roundedStartCap) StrokeCap.Round else StrokeCap.Square))

    val leftRail = Path()
    val rightRail = Path()
    var isFirst = true
    var curD = 0f

    var startP = Offset.Zero
    var startT = Offset.Zero

    while (curD <= length) {
        val p = measure.getPosition(curD)
        val t = measure.getTangent(curD)
        val nx = -t.y * halfSpace
        val ny = t.x * halfSpace
        if (isFirst) {
            startP = p
            startT = t
            leftRail.moveTo(p.x + nx, p.y + ny)
            rightRail.moveTo(p.x - nx, p.y - ny)
            isFirst = false
        } else {
            leftRail.lineTo(p.x + nx, p.y + ny)
            rightRail.lineTo(p.x - nx, p.y - ny)
        }
        curD += 4f
    }
    drawPath(leftRail, color = Color(0xFF535353), style = Stroke(width = 1.2f))
    drawPath(rightRail, color = Color(0xFF535353), style = Stroke(width = 1.2f))

    // Closed top cap
    val nx = -startT.y * halfSpace
    val ny = startT.x * halfSpace
    if (roundedStartCap) {
        val dome = Path().apply {
            moveTo(startP.x + nx, startP.y + ny)
            val topDome = Offset(startP.x - startT.x * halfSpace, startP.y - startT.y * halfSpace)
            quadraticTo(topDome.x, topDome.y, startP.x - nx, startP.y - ny)
        }
        drawPath(dome, color = Color(0xFF535353), style = Stroke(width = 1.2f))
    } else {
        drawLine(
            color = Color(0xFF535353),
            start = Offset(startP.x + nx, startP.y + ny),
            end = Offset(startP.x - nx, startP.y - ny),
            strokeWidth = 1.2f
        )
    }
}

private fun DrawScope.drawLaneWithFootprints(
    path: Path,
    railSpacing: Float,
    footprintStep: Float,
    roundedStartCap: Boolean = false
) {
    drawTwoRailLane(path, railSpacing, roundedStartCap)

    val measure = PathMeasure()
    measure.setPath(path, forceClosed = false)
    val length = measure.length
    val halfSpace = railSpacing / 2f

    var d = footprintStep / 2f
    var side = 1

    while (d < length - footprintStep / 2f) {
        val p = measure.getPosition(d)
        val t = measure.getTangent(d)
        val angle = Math.toDegrees(Math.atan2(t.y.toDouble(), t.x.toDouble())).toFloat()

        val normalX = -t.y * (halfSpace + 3.5.dp.toPx()) * side
        val normalY = t.x * (halfSpace + 3.5.dp.toPx()) * side
        val footCenter = Offset(p.x + normalX, p.y + normalY)

        rotate(degrees = angle, pivot = footCenter) {
            // Sole (oval)
            drawOval(
                color = Color(0xFF1A1A1A),
                topLeft = Offset(footCenter.x - 3.dp.toPx(), footCenter.y - 1.5.dp.toPx()),
                size = Size(6.dp.toPx(), 3.2.dp.toPx())
            )
            // Heel (small circle behind sole)
            drawCircle(
                color = Color(0xFF1A1A1A),
                radius = 1.3.dp.toPx(),
                center = Offset(footCenter.x - 4.2.dp.toPx(), footCenter.y)
            )
        }
        d += footprintStep
        side *= -1
    }
}
